
export const SEARCH_FARMSTAY = "farmstay/SEARCH_FARMSTAY";
export const SEARCH_FARMSTAY_SUCCESS = "farmstay/SEARCH_FARMSTAY_SUCCESS";
export const SEARCH_FARMSTAY_FAILED = "farmstay/SEARCH_FARMSTAY_FAILED";


export const SEARCH_ALL_FARMSTAYS = "farmstay/SEARCH_ALL_FARMSTAYS";
export const SEARCH_ALL_FARMSTAYS_SUCCESS = "farmstay/SEARCH_ALL_FARMSTAYS_SUCCESS";
export const SEARCH_ALL_FARMSTAYS_FAILED = "farmstay/SEARCH_ALL_FARMSTAYS_FAILED";
