
export const SEARCH_FARMSTAY = "farmstay/SEARCH_FARMSTAY";
export const SEARCH_FARMSTAY_SUCCESS = "farmstay/SEARCH_FARMSTAY_SUCCESS";
export const SEARCH_FARMSTAY_FAILED = "farmstay/SEARCH_FARMSTAY_FAILED";


export const SEARCH_ALL_FARMSTAYS = "farmstay/SEARCH_ALL_FARMSTAYS";
export const SEARCH_ALL_FARMSTAYS_SUCCESS = "farmstay/SEARCH_ALL_FARMSTAYS_SUCCESS";
export const SEARCH_ALL_FARMSTAYS_FAILED = "farmstay/SEARCH_ALL_FARMSTAYS_FAILED";

export const GET_FARMSTAY_DETAIL = "farmstay/GET_FARMSTAY_DETAIL";
export const GET_FARMSTAY_DETAIL_SUCCESS = "farmstay/GET_FARMSTAY_DETAIL_SUCCESS";
export const GET_FARMSTAY_DETAIL_FAILED = "farmstay/GET_FARMSTAY_DETAIL_FAILED";
export const CLEAR_FARMSTAY_DETAIL = "farmstay/CLEAR_FARMSTAY_DETAIL";

export const GET_ACTIVITY_DETAIL = "farmstay/GET_ACTIVITY_DETAIL";
export const GET_ACTIVITY_DETAIL_SUCCESS = "farmstay/GET_ACTIVITY_DETAIL_SUCCESS";
export const GET_ACTIVITY_DETAIL_FAILED = "farmstay/GET_ACTIVITY_DETAIL_FAILED";
export const CLEAR_ACTIVITY_DETAIL = "farmstay/CLEAR_FARMSTAY_DETAIL";

export const GET_ACTIVITY_SCHEDULE = "farmstay/GET_ACTIVITY_SCHEDULE";
export const GET_ACTIVITY_SCHEDULE_SUCCESS = "farmstay/GET_ACTIVITY_SCHEDULE_SUCCESS";
export const GET_ACTIVITY_SCHEDULE_FAILED = "farmstay/GET_ACTIVITY_SCHEDULE_FAILED";

export const GET_ROOM_DETAIL = "farmstay/GET_ROOM_DETAIL";
export const GET_ROOM_DETAIL_SUCCESS = "farmstay/GET_ROOM_DETAIL_SUCCESS";
export const GET_ROOM_DETAIL_FAILED = "farmstay/GET_ROOM_DETAIL_FAILED";
export const CLEAR_ROOM_DETAIL = "farmstay/CLEAR_FARMSTAY_DETAIL";

export const GET_ROOM_SCHEDULE = "farmstay/GET_ROOM_SCHEDULE";
export const GET_ROOM_SCHEDULE_SUCCESS = "farmstay/GET_ROOM_SCHEDULE_SUCCESS";
export const GET_ROOM_SCHEDULE_FAILED = "farmstay/GET_ROOM_SCHEDULE_FAILED";
