
export const SEARCH_FARMSTAY = "farmstay/SEARCH_FARMSTAY";
export const SEARCH_FARMSTAY_SUCCESS = "farmstay/SEARCH_FARMSTAY_SUCCESS";
export const SEARCH_FARMSTAY_FAILED = "farmstay/SEARCH_FARMSTAY_FAILED";


export const SEARCH_ALL_FARMSTAYS = "farmstay/SEARCH_ALL_FARMSTAYS";
export const SEARCH_ALL_FARMSTAYS_SUCCESS = "farmstay/SEARCH_ALL_FARMSTAYS_SUCCESS";
export const SEARCH_ALL_FARMSTAYS_FAILED = "farmstay/SEARCH_ALL_FARMSTAYS_FAILED";

export const GET_FARMSTAY_DETAIL = "farmstay/GET_FARMSTAY_DETAIL";
export const GET_FARMSTAY_DETAIL_SUCCESS = "farmstay/GET_FARMSTAY_DETAIL_SUCCESS";
export const GET_FARMSTAY_DETAIL_FAILED = "farmstay/GET_FARMSTAY_DETAIL_FAILED";
export const CLEAR_FARMSTAY_DETAIL = "farmstay/CLEAR_FARMSTAY_DETAIL";

export const GET_ACTIVITY_DETAIL = "farmstay/GET_ACTIVITY_DETAIL";
export const GET_ACTIVITY_DETAIL_SUCCESS = "farmstay/GET_ACTIVITY_DETAIL_SUCCESS";
export const GET_ACTIVITY_DETAIL_FAILED = "farmstay/GET_ACTIVITY_DETAIL_FAILED";
export const CLEAR_ACTIVITY_DETAIL = "farmstay/CLEAR_ACTIVITY_DETAIL";

export const GET_ACTIVITY_SCHEDULE = "farmstay/GET_ACTIVITY_SCHEDULE";
export const GET_ACTIVITY_SCHEDULE_SUCCESS = "farmstay/GET_ACTIVITY_SCHEDULE_SUCCESS";
export const GET_ACTIVITY_SCHEDULE_FAILED = "farmstay/GET_ACTIVITY_SCHEDULE_FAILED";

export const GET_ROOM_DETAIL = "farmstay/GET_ROOM_DETAIL";
export const GET_ROOM_DETAIL_SUCCESS = "farmstay/GET_ROOM_DETAIL_SUCCESS";
export const GET_ROOM_DETAIL_FAILED = "farmstay/GET_ROOM_DETAIL_FAILED";
export const CLEAR_ROOM_DETAIL = "farmstay/CLEAR_ROOM_DETAIL";

export const GET_ROOM_SCHEDULE = "farmstay/GET_ROOM_SCHEDULE";
export const GET_ROOM_SCHEDULE_SUCCESS = "farmstay/GET_ROOM_SCHEDULE_SUCCESS";
export const GET_ROOM_SCHEDULE_FAILED = "farmstay/GET_ROOM_SCHEDULE_FAILED";

export const CREATE_FARMSTAY = "farmstay/CREATE_FARMSTAY";
export const UPDATE_FARMSTAY = "farmstay/UPDATE_FARMSTAY";

export const CREATE_FARMSTAY_POLICIES = "farmstay/CREATE_FARMSTAY_POLICIES";
export const UPDATE_FARMSTAY_POLICIES = "farmstay/UPDATE_FARMSTAY_POLICIES";

export const CREATE_FARMSTAY_SERVICES = "farmstay/CREATE_FARMSTAY_SERVICES";
export const UPDATE_FARMSTAY_SERVICES = "farmstay/UPDATE_FARMSTAY_SERVICES";

export const CREATE_FARMSTAY_ACTIVITIES = "farmstay/CREATE_FARMSTAY_ACTIVITIES";
export const UPDATE_FARMSTAY_ACTIVITIES = "farmstay/UPDATE_FARMSTAY_ACTIVITIES";

export const CREATE_FARMSTAY_ROOMS = "farmstay/CREATE_FARMSTAY_ROOMS";
export const UPDATE_FARMSTAY_ROOMS = "farmstay/UPDATE_FARMSTAY_ROOMS";

export const CREATE_FARMSTAY_FAQS = "farmstay/CREATE_FARMSTAY_FAQS";
export const UPDATE_FARMSTAY_FAQS = "farmstay/UPDATE_FARMSTAY_FAQS";

export const REVIEW_FARMSTAY = "farmstay/REVIEW_FARMSTAY";

export const STORE_PROVINCES = "farmstay/STORE_PROVINCES";
export const STORE_DISTRICTS = "farmstay/STORE_DISTRICTS";
export const STORE_WARDS = "farmstay/STORE_WARDS";

export const UPLOAD_IMAGE = "farmstay/UPLOAD_IMAGE";