
export const SEARCH_SERVICE_CATEGORIES = "service/SEARCH_SERVICE_CATEGORIES";
export const SEARCH_SERVICE_CATEGORIES_SUCCESS = "service/SEARCH_SERVICE_CATEGORIES_SUCCESS";
export const SEARCH_SERVICE_CATEGORIES_FAILED = "service/SEARCH_SERVICE_CATEGORIES_FAILED";

export const GET_ALL_SERVICE_CATEGORIES = "service/GET_ALL_SERVICE_CATEGORIES";
export const GET_ALL_SERVICE_CATEGORIES_SUCCESS = "service/GET_ALL_SERVICE_CATEGORIES_SUCCESS";
export const GET_ALL_SERVICE_CATEGORIES_FAILED = "service/GET_ALL_SERVICE_CATEGORIES_FAILED";

export const CREATE_SERVICE_CATEGORY = "service/CREATE_SERVICE_CATEGORY";
export const CREATE_SERVICE_CATEGORY_SUCCESS = "service/CREATE_SERVICE_CATEGORY_SUCCESS";
export const CREATE_SERVICE_CATEGORY_FAILED = "service/CREATE_SERVICE_CATEGORY_FAILED";

export const UPDATE_SERVICE_CATEGORY = "service/UPDATE_SERVICE_CATEGORY";
export const UPDATE_SERVICE_CATEGORY_SUCCESS = "service/UPDATE_SERVICE_CATEGORY_SUCCESS";
export const UPDATE_SERVICE_CATEGORY_FAILED = "service/UPDATE_SERVICE_CATEGORY_FAILED";

export const GET_SERVICE_CATEGORY_DETAIL = "service/GET_SERVICE_CATEGORY_DETAIL";
export const GET_SERVICE_CATEGORY_DETAIL_SUCCESS = "service/GET_SERVICE_CATEGORY_DETAIL_SUCCESS";
export const GET_SERVICE_CATEGORY_DETAIL_FAILED = "service/GET_SERVICE_CATEGORY_DETAIL_FAILED";
