
export const SEARCH_SERVICE_CATEGORIES = "service/SEARCH_SERVICE_CATEGORIES";
export const SEARCH_SERVICE_CATEGORIES_SUCCESS = "service/SEARCH_SERVICE_CATEGORIES_SUCCESS";
export const SEARCH_SERVICE_CATEGORIES_FAILED = "service/SEARCH_SERVICE_CATEGORIES_FAILED";
