
export const SIGN_IN_HOST = "auth/SIGN_IN_HOST";
export const SIGN_UP_HOST = "auth/SIGN_UP_HOST";
export const SIGN_UP_HOST_SUCCESS = "auth/SIGN_UP_HOST_SUCCESS";

export const SIGN_IN_ADMIN = "auth/SIGN_IN_ADMIN";


export const SIGN_IN_SUCCESS = "auth/SIGN_IN_SUCCESS";

export const SIGN_OUT_USER = "auth/SIGN_OUT_USER";

export const SUBSCRIBE_TOKEN = "auth/SUBSCRIBE_TOKEN";

export const SEARCH_NOTIFICATION = "auth/SEARCH_NOTIFICATION";
export const SEARCH_NOTIFICATION_SUCCESS = "auth/SEARCH_NOTIFICATION_SUCCESS";
export const SEARCH_NOTIFICATION_FAILED = "auth/SEARCH_NOTIFICATION_FAILED";

export const MARK_AS_READ_NOTIFICATION = "auth/MARK_AS_READ_NOTIFICATION";