
export const SEARCH_ROOM_CATEGORIES = "room/SEARCH_ROOM_CATEGORIES";
export const SEARCH_ROOM_CATEGORIES_SUCCESS = "room/SEARCH_ROOM_CATEGORIES_SUCCESS";
export const SEARCH_ROOM_CATEGORIES_FAILED = "room/SEARCH_ROOM_CATEGORIES_FAILED";

export const GET_ALL_ROOM_CATEGORIES = "room/GET_ALL_ROOM_CATEGORIES";
export const GET_ALL_ROOM_CATEGORIES_SUCCESS = "room/GET_ALL_ROOM_CATEGORIES_SUCCESS";
export const GET_ALL_ROOM_CATEGORIES_FAILED = "room/GET_ALL_ROOM_CATEGORIES_FAILED";

export const CREATE_ROOM_CATEGORY = "room/CREATE_ROOM_CATEGORY";
export const CREATE_ROOM_CATEGORY_SUCCESS = "room/CREATE_ROOM_CATEGORY_SUCCESS";
export const CREATE_ROOM_CATEGORY_FAILED = "room/CREATE_ROOM_CATEGORY_FAILED";

export const UPDATE_ROOM_CATEGORY = "room/UPDATE_ROOM_CATEGORY";
export const UPDATE_ROOM_CATEGORY_SUCCESS = "room/UPDATE_ROOM_CATEGORY_SUCCESS";
export const UPDATE_ROOM_CATEGORY_FAILED = "room/UPDATE_ROOM_CATEGORY_FAILED";

export const GET_ROOM_CATEGORY_DETAIL = "room/GET_ROOM_CATEGORY_DETAIL";
export const GET_ROOM_CATEGORY_DETAIL_SUCCESS = "room/GET_ROOM_CATEGORY_DETAIL_SUCCESS";
export const GET_ROOM_CATEGORY_DETAIL_FAILED = "room/GET_ROOM_CATEGORY_DETAIL_FAILED";
