
export const SEARCH_ROOM_CATEGORIES = "room/SEARCH_ROOM_CATEGORIES";
export const SEARCH_ROOM_CATEGORIES_SUCCESS = "room/SEARCH_ROOM_CATEGORIES_SUCCESS";
export const SEARCH_ROOM_CATEGORIES_FAILED = "room/SEARCH_ROOM_CATEGORIES_FAILED";
