
export const SEARCH_ORDERS = "order/SEARCH_ORDERS";
export const SEARCH_ORDERS_SUCCESS = "order/SEARCH_ORDERS_SUCCESS";
export const SEARCH_ORDERS_FAILED = "order/SEARCH_ORDERS_FAILED";


export const SEARCH_DISBURSEMENTS = "order/SEARCH_DISBURSEMENTS";
export const SEARCH_DISBURSEMENTS_SUCCESS = "order/SEARCH_DISBURSEMENTS_SUCCESS";
export const SEARCH_DISBURSEMENTS_FAILED = "order/SEARCH_DISBURSEMENTS_FAILED";
