
export const SEARCH_ORDERS = "order/SEARCH_ORDERS";
export const SEARCH_ORDERS_SUCCESS = "order/SEARCH_ORDERS_SUCCESS";
export const SEARCH_ORDERS_FAILED = "order/SEARCH_ORDERS_FAILED";

export const SEARCH_DISBURSEMENTS = "order/SEARCH_DISBURSEMENTS";
export const SEARCH_DISBURSEMENTS_SUCCESS = "order/SEARCH_DISBURSEMENTS_SUCCESS";
export const SEARCH_DISBURSEMENTS_FAILED = "order/SEARCH_DISBURSEMENTS_FAILED";

export const GET_ORDER_DETAIL = "order/GET_ORDER_DETAIL";
export const GET_ORDER_DETAIL_SUCCESS = "order/GET_ORDER_DETAIL_SUCCESS";
export const GET_ORDER_DETAIL_FAILED = "order/GET_ORDER_DETAIL_FAILED";
export const CLEAR_ORDER_DETAIL = "order/CLEAR_ORDER_DETAIL";

export const GET_DISBURSEMENT_DETAIL = "order/GET_DISBURSEMENT_DETAIL";
export const GET_DISBURSEMENT_DETAIL_SUCCESS = "order/GET_DISBURSEMENT_DETAIL_SUCCESS";
export const GET_DISBURSEMENT_DETAIL_FAILED = "order/GET_DISBURSEMENT_DETAIL_FAILED";
export const CLEAR_DISBURSEMENT_DETAIL = "order/CLEAR_DISBURSEMENT_DETAIL";

export const REVIEW_BOOKING = "order/REVIEW_BOOKING";
