
export const SEARCH_FEEDBACKS = "feedback/SEARCH_FEEDBACKS";
export const SEARCH_FEEDBACKS_SUCCESS = "feedback/SEARCH_FEEDBACKS_SUCCESS";
export const SEARCH_FEEDBACKS_FAILED = "feedback/SEARCH_FEEDBACKS_FAILED";

export const UPDATE_FEEDBACK_STATUS = "feedback/UPDATE_FEEDBACK_STATUS";

export const HOST_REPORT_FEEDBACK = "feedback/HOST_REPORT_FEEDBACK";