
export const SEARCH_HOSTS = "user/SEARCH_HOSTS";
export const SEARCH_HOSTS_SUCCESS = "user/SEARCH_HOSTS_SUCCESS";
export const SEARCH_HOSTS_FAILED = "user/SEARCH_HOSTS_FAILED";

export const SEARCH_CUSTOMERS = "user/SEARCH_CUSTOMERS";
export const SEARCH_CUSTOMERS_SUCCESS = "user/SEARCH_CUSTOMERS_SUCCESS";
export const SEARCH_CUSTOMERS_FAILED = "user/SEARCH_CUSTOMERS_FAILED";

export const SEARCH_ADMINS = "user/SEARCH_ADMINS";
export const SEARCH_ADMINS_SUCCESS = "user/SEARCH_ADMINS_SUCCESS";
export const SEARCH_ADMINS_FAILED = "user/SEARCH_ADMINS_FAILED";

export const SEARCH_USERS = "user/SEARCH_USERS";
export const SEARCH_USERS_SUCCESS = "user/SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_FAILED = "user/SEARCH_USERS_FAILED";

// All
export const SEARCH_ALL_HOSTS = "user/SEARCH_ALL_HOSTS";
export const SEARCH_ALL_HOSTS_SUCCESS = "user/SEARCH_ALL_HOSTS_SUCCESS";
export const SEARCH_ALL_HOSTS_FAILED = "user/SEARCH_ALL_HOSTS_FAILED";

export const SEARCH_ALL_CUSTOMERS = "user/SEARCH_ALL_CUSTOMERS";
export const SEARCH_ALL_CUSTOMERS_SUCCESS = "user/SEARCH_ALL_CUSTOMERS_SUCCESS";
export const SEARCH_ALL_CUSTOMERS_FAILED = "user/SEARCH_ALL_CUSTOMERS_FAILED";

export const SEARCH_ALL_ADMINS = "user/SEARCH_ALL_ADMINS";
export const SEARCH_ALL_ADMINS_SUCCESS = "user/SEARCH_ALL_ADMINS_SUCCESS";
export const SEARCH_ALL_ADMINS_FAILED = "user/SEARCH_ALL_ADMINS_FAILED";

export const SEARCH_ALL_USERS = "user/SEARCH_ALL_USERS";
export const SEARCH_ALL_USERS_SUCCESS = "user/SEARCH_ALL_USERS_SUCCESS";
export const SEARCH_ALL_USERS_FAILED = "user/SEARCH_ALL_USERS_FAILED";

export const GET_USER_DETAIL = "user/GET_USER_DETAIL";
export const GET_USER_DETAIL_SUCCESS = "user/GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_FAILED = "user/GET_USER_DETAIL_FAILED";
export const CLEAR_USER_DETAIL = "user/CLEAR_HOST_DETAIL";


// ACCOUNT
export const UPDATE_HOST_MY_PROFILE = "user/UPDATE_HOST_MY_PROFILE";
export const UPDATE_HOST_MY_PROFILE_SUCCESS = "user/UPDATE_HOST_MY_PROFILE_SUCCESS";
export const UPDATE_HOST_MY_PROFILE_FAILED = "user/UPDATE_HOST_MY_PROFILE_FAILED";

export const UPDATE_ADMIN_MY_PROFILE = "user/UPDATE_ADMIN_MY_PROFILE";
export const UPDATE_ADMIN_MY_PROFILE_SUCCESS = "user/UPDATE_ADMIN_MY_PROFILE_SUCCESS";
export const UPDATE_ADMIN_MY_PROFILE_FAILED = "user/UPDATE_ADMIN_MY_PROFILE_FAILED";

