
export const SEARCH_TAG_CATEGORIES = "tag/SEARCH_TAG_CATEGORIES";
export const SEARCH_TAG_CATEGORIES_SUCCESS = "tag/SEARCH_TAG_CATEGORIES_SUCCESS";
export const SEARCH_TAG_CATEGORIES_FAILED = "tag/SEARCH_TAG_CATEGORIES_FAILED";

export const GET_ALL_TAG_CATEGORIES = "tag/GET_ALL_TAG_CATEGORIES";
export const GET_ALL_TAG_CATEGORIES_SUCCESS = "tag/GET_ALL_TAG_CATEGORIES_SUCCESS";
export const GET_ALL_TAG_CATEGORIES_FAILED = "tag/GET_ALL_TAG_CATEGORIES_FAILED";


export const CREATE_TAG = "tag/CREATE_TAG";
export const CREATE_TAG_SUCCESS = "tag/CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAILED = "tag/CREATE_TAG_FAILED";

export const UPDATE_TAG = "tag/UPDATE_TAG";
export const UPDATE_TAG_SUCCESS = "tag/UPDATE_TAG_SUCCESS";
export const UPDATE_TAG_FAILED = "tag/UPDATE_TAG_FAILED";

export const GET_TAG_DETAIL = "tag/GET_TAG_DETAIL";
export const GET_TAG_DETAIL_SUCCESS = "tag/GET_TAG_DETAIL_SUCCESS";
export const GET_TAG_DETAIL_FAILED = "tag/GET_TAG_DETAIL_FAILED";

